### ISSUE TITLE
Semana 10 - Clase 10 - Video 1-2 PYTHON

### ISSUE THREAD

**Issue by NahuelTapia** [CodeSystem2022/Tercer-Semestre-Grupo-Bestias-Binarias-#102]
Le toca hacer los primeros dos videos de Laboratorio 3 de la clase 10 en Python

**Comment by DaianaEscudero** [comment]
Buenas tardes señor pre cumpleañero, agrego los puntos asignados!!

**Comment by NahuelTapia** [comment]
Genial Señora, le felicito por su puntualidad.
