### ISSUE TITLE
Semana 10 - Clase 10 - Video 3-4 Python

### ISSUE THREAD

**Issue by NahuelTapia** [CodeSystem2022/Tercer-Semestre-Grupo-Bestias-Binarias-#103]
Le toco hacer los videos 3 y 4 de la clase 10 en Laboratorio y pestaña Python

**Comment by DanielGuerrero03** [comment]
Listo, agregado parte 3 y 4 de la clase 10 Python como se pidio! Saludos! Cumpleañero!

**Comment by NahuelTapia** [comment]
Muy bien su aporte, lo felicito.
