### ISSUE TITLE
Semana 10 - Clase 10 - Video 5 Python

### ISSUE THREAD

**Issue by NahuelTapia** [CodeSystem2022/Tercer-Semestre-Grupo-Bestias-Binarias-#104]
Le toco hacer lo último de Python porque no hay preferencia.

**Comment by FernandoSilva12** [comment]
Buen finde nahu y feliz cumple, ahí quedo agregado lo solicitado abrazo grande

**Comment by NahuelTapia** [comment]
Gracias y felicitaciones por lograr lo solicitado!
